#!/bin/bash

code_pathfile="$HOME/.VAR_CODE_PATH"
dotfiles_pathfile="$HOME/.VAR_DOTFILES_BASE_PATH"
platform="$(uname)"

if [ ! -f "$code_pathfile" ] || [ ! -f "$dotfiles_pathfile" ]
then
    echo "ERROR: Missing either $code_pathfile OR $dotfiles_pathfile"
    echo "Halting ${BASH_SOURCE[0]}"
    return 1
fi

source "$HOME/.exports"
source "$HOME/lib/common.lib.sh"
source "$HOME/lib/common-bash.lib.sh"
source "$HOME/lib/${platform}.lib.sh"
source "$HOME/.bash_prompt"

# For dotfile module add-on configs
[ -e ~/.dotfile_config_module ] && source ~/.dotfile_config_module

# For local add-on configs
[ -e ~/.dotfile_config_local ] && source ~/.dotfile_config_local

[ -e ~/.bash_aliases ] && source ~/.bash_aliases


##############################################
# COMPLETIONS
##############################################

# bash completions
[ -f /etc/bash_completion ] && source /etc/bash_completion

# Add tab completion for SSH hostnames based
#   on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2- | tr ' ' '\n')" scp sftp ssh;

# show date | week | day of year
date_date_week_DOY
