#!/bin/zsh

code_pathfile="$HOME/.VAR_CODE_PATH"
dotfiles_base_pathfile="$HOME/.VAR_DOTFILES_BASE_PATH"
platform="$(uname)"

if [ ! -f "$code_pathfile" ] || [ ! -f "$dotfiles_base_pathfile" ]
then
    echo "ERROR: Missing either $code_pathfile OR $dotfiles_base_pathfile"
    echo "Halting ${BASH_SOURCE[0]}"
    return 1
fi

source "$HOME/.exports"
source "$HOME/.lib/common.lib.sh"
source "$HOME/.lib/common-zsh.lib.sh"
source "$HOME/.lib/${platform}.lib.sh"
source "$HOME/.zsh_prompt"

# For dotfile module add-on configs
[ -e ~/.dotfile_config_module ] && source ~/.dotfile_config_module

# For local add-on configs
[ -e ~/.dotfile_config_local ] && source ~/.dotfile_config_local

date_date_week_DOY
